/** Monochrome Unicode symbols — mathematical, technical, alchemical-adjacent */
export const sym = {
  search: '⌕',
  lookup: '⎔',
  add: '⊕',
  folder: '⊞',
  download: '⇩',
  preview: '◧',
  document: '⊡',
  back: '◂',
  prev: '◂',
  next: '▸',
  remove: '⊗',
  edit: '✎',
  close: '⊗',
  warn: '⚠',
  swipe: '⇔',
  text: '𝔄',
  fontDecrease: '−',
  fontIncrease: '＋',
  darkMode: '◐',
  lightMode: '◑',
  filter: '⎍',
  sort: '⇅',
  empty: '∅',
  more: '⋯',
} as const;
