/** Monochrome Unicode symbols — widely supported across platforms */
export const sym = {
  brand: 'ℵ',
  search: '⌕',
  add: '＋',
  folder: '▤',
  download: '↓',
  document: '▤',
  back: '‹',
  prev: '‹',
  next: '›',
  remove: '✕',
  edit: '✎',
  close: '✕',
  warn: '⚠',
  swipe: '⇔',
  text: 'Aa',
  fontDecrease: '−',
  fontIncrease: '＋',
  darkMode: '☾',
  lightMode: '☀',
} as const;
